### ISSUE TITLE
support for other content type

### ISSUE THREAD

**Issue by ghost** [DoumanAsh/fie#4]
Would it be possible to add support for other `POST` payloads such as videos and blogs?

**Comment by DoumanAsh** [comment]
I generally try to use only what accessible by all three social medias.

I think blogs are purely minds.com thing?
While videos are not available on gab.ai.

But I need to look it up

**Comment by ghost** [comment]
@DoumanAsh Also, if it's possible, https://www.real.video/ and https://www.bitchute.com

**Comment by DoumanAsh** [comment]
As blogs and videos are not possible with all supported platforms I'm closing this one.

If someone would like to have other content types, please create separate issue and _confirm_ that this content type is supported by all twitter, gab/mastodon, minds
